GET http://localhost:3000/api/offers
###
GET http://localhost:3000/api/offers/3DD_SH
###
GET http://localhost:3000/api/offers/1
###
DELETE http://localhost:3000/api/offers/rFVOIO
###
GET http://localhost:3000/api/offers/rFVOIO
###
POST http://localhost:3000/api/offers
content-type: application/json

{
    "name": "test"
}
###
POST http://localhost:3000/api/offers
content-type: application/json

{
    "picture": "test",
    "title": "Продам гараж",
    "description": "Любые проверки на месте. Пользовались 2-3 раза",
    "category": [
      "Авто"
    ],
    "sum": 1000,
    "type": "OFFER"
}
###
PUT  http://localhost:3000/api/offers/Msdbj0
content-type: application/json

{
    "picture": "test 2",
    "title": "Продам гараж",
    "description": "Пользовались 2-3 раза",
    "category": [
      "Авто"
    ],
    "sum": 1001,
    "type": "OFFER"
}
###
GET http://localhost:3000/api/offers/3DD_SH/comments
###
DELETE http://localhost:3000/api/offers/3DD_SH/comments/k7dHQQ
###
POST http://localhost:3000/api/offers/3DD_SH/comments
content-type: application/json

{
    "text": "test comment 123231 "
}
###
POST http://localhost:3000/api/user
content-type: application/json

{
    "email": "user@local.localhost",
    "name": "User Name",
    "password": "111111",
    "confirm_password": "111111"
}
###
POST http://localhost:3000/api/user/login
content-type: application/json

{
    "email": "user@local.localhost",
    "password": "111111"
}

###
POST http://localhost:3000/api/user/refresh
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE2OTI3NTkyfQ.QWkmp-BNEpxEIkmaexCMY2cfAiL_5vt2hfSzJyC-UpU"
}

###
DELETE http://localhost:3000/api/user/logout
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE2OTI3NTkyLCJleHAiOjE2MTY5Mjc4OTJ9.3Tkg8HDSkh-N8Vxxtv7jee9Hk1dqgKH-fAwTXUoGS5Q
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE2OTI3NTkyfQ.QWkmp-BNEpxEIkmaexCMY2cfAiL_5vt2hfSzJyC-UpU"
}
